@startuml sequence
participant User
participant Browser
participant Server
participant Session
participant Database

User -> Browser : Actions
activate Browser
Browser -> Server : POST
activate Server
Server -> Database : UPDATE
activate Database
Server <-- Database : Done
deactivate Database
Server ->> Session : save some\nattributes
activate Session #f8bbd0
Browser <-- Server : Redirect
deactivate Server
Browser -> Server : GET
activate Server
Server <<-- Session : laod the\nattributes
deactivate Session
Server -> Database : SELECT
activate Database
Server <-- Database : Records
deactivate Database
Browser <-- Server : HTML
deactivate Server
User <-- Browser : Show HTML
deactivate Browser
@enduml